# Generated by Django 3.1.6 on 2021-02-11 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productid', models.CharField(max_length=10)),
                ('userid', models.CharField(max_length=10)),
                ('profilename', models.CharField(max_length=100)),
                ('helpfulness', models.CharField(max_length=3)),
                ('score', models.FloatField()),
                ('time', models.BigIntegerField()),
                ('summary', models.TextField(max_length=100)),
                ('text', models.TextField(max_length=100)),
            ],
        ),
    ]
